apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      log_format my_format '... host: $host, http_host: $http_host ...';
      access_log /var/log/nginx/access.log my_format;
  
      server {
        listen 80;

        location /products {
          proxy_pass http://pss-app-service:8081/pms/products;
        }
        
        location /productById/ {
            proxy_pass http://pss-app-service:8081/pms/productById/;
        }

        location /product/ {
            proxy_pass http://pss-app-service:8081/pms/productByName/;
        }
        
        location /addProduct {
          proxy_pass http://pas-app-service:8080/pms/addProduct;
        }
        
        location /update {
            proxy_pass http://pas-app-service:8080/pms/update;
        }

        location /delete/ {
            proxy_pass http://pas-app-service:8080/pms/delete/;
        }
      }
      
    }
